;;; gomuks-tests.el --- Tests for gomuks.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'gomuks)

(ert-deftest gomuks-uses-auth-source-and-allows-session-override ()
  (let ((gomuks-backend-url "https://chat.example:8443")
        (gomuks-username nil)
        (gomuks--password nil)
        (gomuks--skip-auth-source nil)
        (gomuks--stream nil)
        (queries nil))
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest args)
                 (push args queries)
                 (list (list :user "stored-user"
                             :secret (lambda () "stored-password")))))
              ((symbol-function 'gomuks-home) #'ignore)
              ((symbol-function 'gomuks--start-stream) #'ignore)
              ((symbol-function 'read-string)
               (lambda (&rest _) (error "Unexpected username prompt")))
              ((symbol-function 'read-passwd)
               (lambda (&rest _) (error "Unexpected password prompt"))))
      (gomuks)
      (should (equal gomuks-username "stored-user"))
      (should (equal gomuks--password "stored-password"))
      (should (equal (plist-get (car queries) :host) "chat.example"))
      (should (equal (plist-get (car queries) :port) "8443")))
    (setq gomuks-username nil gomuks--password nil
          gomuks--skip-auth-source t)
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest _) (error "Stored credentials were reused")))
              ((symbol-function 'gomuks-home) #'ignore)
              ((symbol-function 'gomuks--start-stream) #'ignore)
              ((symbol-function 'read-string) (lambda (&rest _) "new-user"))
              ((symbol-function 'read-passwd) (lambda (&rest _) "new-password")))
      (gomuks)
      (should (equal gomuks-username "new-user"))
      (should (equal gomuks--password "new-password")))))

(ert-deftest gomuks-echo-area-notifications-follow-selected-buffer ()
  (let ((gomuks-echo-area-notifications 'in-gomuks))
    (save-window-excursion
      (with-temp-buffer
        (switch-to-buffer (current-buffer))
        (should-not (gomuks--echo-area-notifications-p))
        (gomuks-room-mode)
        (should (gomuks--echo-area-notifications-p))
        (setq gomuks-echo-area-notifications nil)
        (should-not (gomuks--echo-area-notifications-p))
        (setq gomuks-echo-area-notifications t)
        (should (gomuks--echo-area-notifications-p))))))

(ert-deftest gomuks-sync-renders-room-and-messages ()
  (let ((gomuks--rooms (make-hash-table :test 'equal))
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--member-state (make-hash-table :test 'equal))
        (gomuks--requested-members (make-hash-table :test 'equal))
        (gomuks--timelines (make-hash-table :test 'equal))
        (gomuks--timeline-ids (make-hash-table :test 'equal)))
    (unwind-protect
        (save-window-excursion
          (with-current-buffer (get-buffer-create "*Gomuks*")
            (gomuks-rooms-mode))
          (gomuks--apply-sync
           '((rooms . (("!room:test" .
                       ((meta . ((name . "Test room")
                                 (sorting_timestamp . 123)))
                        (state . ((m.room.member . (("@a:test" . 12)))))
                        (events . (((rowid . 12) (type . "m.room.member")
                                    (state_key . "@a:test")
                                    (content . ((membership . "join")
                                                (displayname . "Alice Example"))))
                                   ((rowid . 10) (event_id . "$one")
                                    (sender . "@a:test")
                                    (type . "m.room.message")
                                    (timestamp . 100000)
                                    (content . ((body . "Hello"))))
                                   ((rowid . 11) (event_id . "$two")
                                    (sender . "@a:test")
                                    (type . "m.room.message")
                                    (timestamp . 101000)
                                    (content . ((body . "Second"))))))
                        (timeline . (((timeline_rowid . 1)
                                      (event_rowid . 10))
                                     ((timeline_rowid . 2)
                                      (event_rowid . 11))))))))))
          (with-current-buffer "*Gomuks*"
            (should (string-match-p "Test room" (buffer-string)))
            (goto-char (point-min))
            (search-forward "Test room")
            (gomuks-open-room))
          (with-current-buffer "*Gomuks: !room:test*"
            (should (string-match-p "Alice Example" (buffer-string)))
            (should-not (string-match-p "@a:test" (buffer-string)))
            (should (string-match-p "Hello" (buffer-string)))
            (should (string-match-p "Hello\n[0-9: ]+│  Second" (buffer-string)))
            (goto-char (point-min))
            (search-forward "Alice Example")
            (should (equal (get-text-property (1- (point)) 'help-echo) "@a:test"))
            (goto-char (point-min))
            (search-forward "Hello")
            (should (equal "$one"
                           (gomuks--alist 'event_id (gomuks--event-at-point))))
            (gomuks-copy-sender-id)
            (should (equal (current-kill 0) "@a:test")))
          (should (get-buffer "*Gomuks compose: !room:test*"))
          (should (get-buffer-window "*Gomuks compose: !room:test*")))
      (dolist (name '("*Gomuks*" "*Gomuks: !room:test*"
                      "*Gomuks compose: !room:test*"))
        (when-let* ((buffer (get-buffer name))) (kill-buffer buffer))))))

(ert-deftest gomuks-open-room-loads-first-history-page-once ()
  (let ((gomuks--rooms (make-hash-table :test 'equal))
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--member-state (make-hash-table :test 'equal))
        (gomuks--requested-members (make-hash-table :test 'equal))
        (gomuks--timelines (make-hash-table :test 'equal))
        (gomuks--timeline-ids (make-hash-table :test 'equal))
        (gomuks--stream nil)
        (requests 0)
        (id "!initial:test"))
    (unwind-protect
        (save-window-excursion
          (puthash id '((name . "Initial room")) gomuks--rooms)
          (with-current-buffer (get-buffer-create "*Gomuks test home*")
            (gomuks-rooms-mode)
            (let ((inhibit-read-only t))
              (insert "Initial room\n")
              (put-text-property (point-min) (point-max) 'gomuks-room-id id))
            (goto-char (point-min)))
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (should (equal command "paginate"))
                       (should (= (gomuks--alist 'limit data) 50))
                       (setq requests (1+ requests))
                       (funcall callback nil
                                '((events . (((rowid . 1)
                                              (timeline_rowid . 1)
                                              (room_id . "!initial:test")
                                              (event_id . "$initial")
                                              (type . "m.room.message")
                                              (sender . "@a:test")
                                              (content . ((body . "First page")))))))))))
            (with-current-buffer "*Gomuks test home*"
              (goto-char (point-min))
              (gomuks-open-room))
            (should (= requests 1))
            (with-current-buffer (format "*Gomuks: %s*" id)
              (should (string-match-p "First page" (buffer-string))))
            (with-current-buffer "*Gomuks test home*" (gomuks-open-room))
            (should (= requests 1))))
      (dolist (name (list "*Gomuks test home*" (format "*Gomuks: %s*" id)
                          (format "*Gomuks compose: %s*" id)))
        (when-let* ((buffer (get-buffer name))) (kill-buffer buffer))))))

(ert-deftest gomuks-room-render-keeps-scroll-position-and-bottom ()
  (let ((gomuks--rooms (make-hash-table :test 'equal))
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--timelines (make-hash-table :test 'equal))
        (gomuks--member-state (make-hash-table :test 'equal))
        (gomuks--requested-members (make-hash-table :test 'equal))
        (gomuks--stream nil)
        (id "!scroll:test")
        (room (generate-new-buffer "*gomuks-scroll-test*")))
    (unwind-protect
        (save-window-excursion
          (dotimes (index 80)
            (let ((rowid (1+ index)))
              (puthash rowid
                       `((rowid . ,rowid) (room_id . ,id)
                         (event_id . ,(format "$%s" rowid))
                         (sender . "@a:test") (type . "m.room.message")
                         (timestamp . ,(* rowid 60000))
                         (content . ((body . ,(format "Message %s" rowid)))))
                       gomuks--events)))
          (puthash id (number-sequence 1 80) gomuks--timelines)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id id))
          (switch-to-buffer room)
          (gomuks--render-buffer room id)
          (let ((window (selected-window)))
            (with-current-buffer room
              (let ((position (text-property-any (point-min) (point-max)
                                                 'gomuks-event-rowid 10)))
                (set-window-point window position)
                (set-window-start window position t)
                (redisplay t))
              (let ((before (get-text-property (window-start window)
                                               'gomuks-event-rowid)))
                (should (and before (< before 80)))
              (puthash 81
                       `((rowid . 81) (room_id . ,id) (event_id . "$81")
                         (sender . "@a:test") (type . "m.room.message")
                         (timestamp . 4860000)
                         (content . ((body . "Message 81"))))
                       gomuks--events)
              (puthash id (number-sequence 1 81) gomuks--timelines)
              (gomuks--render-buffer room id)
              (should (equal (get-text-property (window-start window)
                                                'gomuks-event-rowid) before)))
              (goto-char (point-max))
              (recenter -1)
              (let* ((composer (generate-new-buffer "*gomuks-scroll-composer-test*"))
                     (composer-window (split-window window -6 'below)))
                (unwind-protect
                    (progn
                      (set-window-buffer composer-window composer)
                      (with-selected-window window
                        (goto-char (point-max))
                        (recenter -1))
                      (select-window composer-window)
                      (puthash 82
                               `((rowid . 82) (room_id . ,id) (event_id . "$82")
                                 (sender . "@a:test") (type . "m.room.message")
                                 (timestamp . 4920000)
                                 (content . ((body . "Message 82"))))
                               gomuks--events)
                      (puthash id (number-sequence 1 82) gomuks--timelines)
                      (gomuks--render-buffer room id)
                      (should (= (window-point window)
                                 (with-current-buffer room (point-max)))))
                  (kill-buffer composer))))))
      (kill-buffer room))))

(ert-deftest gomuks-reply-uses-matrix-relation ()
  (let ((sent nil))
    (cl-letf (((symbol-function 'gomuks--post)
               (lambda (command data _callback)
                 (setq sent (cons command data)))))
      (with-temp-buffer
        (gomuks-room-mode)
        (setq gomuks--room-id "!room:test")
        (let ((inhibit-read-only t))
          (insert "message\n")
          (put-text-property (point-min) (point-max) 'gomuks-event
                             '((event_id . "$event"))))
        (goto-char (point-min))
        (gomuks-reply "reply")))
    (should (equal (car sent) "send_message"))
    (should (equal (gomuks--alist 'event_id
                                  (gomuks--alist 'm.in_reply_to
                                                 (gomuks--alist 'relates_to (cdr sent))))
                   "$event"))
    (should (string-match-p "m.in_reply_to"
                            (json-serialize (cdr sent))))))

(ert-deftest gomuks-active-room-marks-newest-visible-message-read ()
  (let ((gomuks--rooms (make-hash-table :test 'equal))
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--timelines (make-hash-table :test 'equal))
        (gomuks--last-read (make-hash-table :test 'equal))
        (room (generate-new-buffer "*gomuks-read-test*"))
        (other (generate-new-buffer "*gomuks-other-test*"))
        (sent nil))
    (unwind-protect
        (save-window-excursion
          (puthash "!room:test" '((unread_messages . 2)) gomuks--rooms)
          (puthash 1 '((rowid . 1) (event_id . "$latest")) gomuks--events)
          (puthash "!room:test" '(1) gomuks--timelines)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id "!room:test")
            (let ((inhibit-read-only t)) (insert "latest\n")))
          (switch-to-buffer room)
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (push (cons command data) sent)
                       (funcall callback nil nil))))
            (gomuks--maybe-mark-read)
            (gomuks--maybe-mark-read)
            (should (= (length sent) 1))
            (should (equal (gomuks--alist 'event_id (cdar sent)) "$latest"))
            (switch-to-buffer other)
            (clrhash gomuks--last-read)
            (gomuks--maybe-mark-read)
            (should (= (length sent) 1))))
      (kill-buffer room)
      (kill-buffer other))))

(ert-deftest gomuks-reply-preview-follows-parent ()
  (let* ((gomuks--events (make-hash-table :test 'equal))
         (parent '((rowid . 1) (room_id . "!room:test")
                   (event_id . "$parent") (sender . "@a:test")
                   (type . "m.room.message")
                   (content . ((body . "Original")))))
         (reply '((rowid . 2) (room_id . "!room:test")
                  (event_id . "$reply") (sender . "@b:test")
                  (type . "m.room.message")
                  (content . ((body . "> <@a:test> Original\n\nAnswer")
                              (m.relates_to . ((m.in_reply_to .
                                                ((event_id . "$parent")))))))))
         (room (generate-new-buffer "*gomuks-reply-test*")))
    (unwind-protect
        (save-window-excursion
          (puthash 1 parent gomuks--events)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id "!room:test")
            (let ((inhibit-read-only t))
              (gomuks--insert-event parent)
              (gomuks--insert-event reply))
            (should (string-match-p "↪ a: Original" (buffer-string)))
            (should-not (string-match-p "> <@a:test>" (buffer-string))))
          (switch-to-buffer room)
          (goto-char (point-min))
          (search-forward "Answer")
          (gomuks-follow-reply)
          (should (equal (gomuks--alist 'event_id (gomuks--event-at-point))
                         "$parent")))
      (kill-buffer room))))

(ert-deftest gomuks-search-pages-and-returns-from-result-context ()
  (let* ((gomuks--rooms (make-hash-table :test 'equal))
         (gomuks--events (make-hash-table :test 'equal))
         (gomuks--member-state (make-hash-table :test 'equal))
         (gomuks--requested-members (make-hash-table :test 'equal))
         (gomuks--stream nil)
         (id "!search:test")
         (first '((rowid . 1) (room_id . "!search:test")
                  (event_id . "$first") (sender . "@a:test")
                  (type . "m.room.message")
                  (content . ((body . "first match")))))
         (second '((rowid . 2) (room_id . "!search:test")
                   (event_id . "$second") (sender . "@a:test")
                   (type . "m.room.message")
                   (content . ((body . "second match")))))
         (room (generate-new-buffer "*gomuks-search-source-test*"))
         (search-name (format "*Gomuks search: %s*" id))
         (context-name "*Gomuks context: $first*")
         (requests nil))
    (unwind-protect
        (save-window-excursion
          (puthash id '((name . "Search room")) gomuks--rooms)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id id))
          (switch-to-buffer room)
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "match"))
                    ((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (push (cons command data) requests)
                       (pcase command
                         ("search_local"
                          (funcall callback nil
                                   (if (gomuks--alist 'next_batch data)
                                       `((events . (,second)))
                                     `((events . (,first))
                                       (next_batch . "next")))))
                         ("get_event_context"
                          (funcall callback nil `((event . ,first))))))))
            (gomuks-search)
            (with-current-buffer search-name
              (should (= (length gomuks--search-results) 1))
              (should (equal gomuks--search-next-batch "next"))
              (gomuks-search-more)
              (should (= (length gomuks--search-results) 2))
              (should-not gomuks--search-next-batch)
              (goto-char (point-min))
              (search-forward "first match")
              (gomuks-search-open))
            (should (equal (gomuks--alist 'next_batch
                                         (cdr (cadr requests))) "next"))
            (with-current-buffer context-name (gomuks-back))
            (should (eq (window-buffer (selected-window))
                        (get-buffer search-name)))
            (with-current-buffer search-name (gomuks-search-back))
            (should (eq (window-buffer (selected-window)) room))))
      (dolist (name (list search-name context-name
                          (format "*Gomuks compose: %s*" id)
                          (format "*Gomuks compose: %s $first*" id)))
        (when-let* ((buffer (get-buffer name))) (kill-buffer buffer)))
      (kill-buffer room))))

(ert-deftest gomuks-request-keeps-buffer-displayed-by-callback ()
  (let ((response-buffer nil)
        (target (generate-new-buffer "*gomuks-request-target-test*")))
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'url-retrieve)
                     (lambda (_url callback &rest _)
                       (setq response-buffer
                             (generate-new-buffer " *gomuks-response-test*"))
                       (with-current-buffer response-buffer
                         (insert "HTTP/1.1 200 OK\r\n\r\n{}")
                         (setq-local url-http-response-status 200)
                         (funcall callback nil)))))
            (gomuks--request
             "test" "{}"
             (lambda (failure _response)
               (should-not failure)
               (switch-to-buffer target))))
          (should-not (buffer-live-p response-buffer))
          (should (buffer-live-p target)))
      (when (buffer-live-p response-buffer) (kill-buffer response-buffer))
      (kill-buffer target))))

(ert-deftest gomuks-thread-reply-keeps-thread-relation ()
  (let (sent)
    (cl-letf (((symbol-function 'gomuks--post)
               (lambda (_command data _callback) (setq sent data))))
      (with-temp-buffer
        (gomuks-room-mode)
        (setq gomuks--room-id "!room:test"
              gomuks--thread-root "$root")
        (let ((inhibit-read-only t))
          (insert "reply\n")
          (put-text-property (point-min) (point-max) 'gomuks-event
                             '((event_id . "$parent"))))
        (goto-char (point-min))
        (gomuks-reply "inside thread")))
    (let ((relation (gomuks--alist 'relates_to sent)))
      (should (equal (gomuks--alist 'rel_type relation) "m.thread"))
      (should (equal (gomuks--alist 'event_id relation) "$root"))
      (should (equal (gomuks--alist 'event_id
                                   (gomuks--alist 'm.in_reply_to relation))
                     "$parent")))))

(ert-deftest gomuks-thread-opens-from-reply-and-merges-history ()
  (let* ((gomuks--events (make-hash-table :test 'equal))
         (gomuks--rooms (make-hash-table :test 'equal))
         (gomuks--timelines (make-hash-table :test 'equal))
         (root '((rowid . 1) (room_id . "!room:test")
                 (event_id . "$root") (sender . "@a:test")
                 (type . "m.room.message") (timestamp . 1000)
                 (content . ((body . "Root")))))
         (early '((rowid . 2) (room_id . "!room:test")
                  (event_id . "$early") (sender . "@b:test")
                  (type . "m.room.message") (timestamp . 3000)
                  (relates_to . "$root") (relation_type . "m.thread")
                  (content . ((body . "Early")))))
         (late '((rowid . 3) (room_id . "!room:test")
                 (event_id . "$late") (sender . "@b:test")
                 (type . "m.room.message") (timestamp . 4000)
                 (relates_to . "$root") (relation_type . "m.thread")
                 (content . ((body . "Late")))))
         (older '((rowid . 4) (room_id . "!room:test")
                  (event_id . "$older") (sender . "@b:test")
                  (type . "m.room.message") (timestamp . 2000)
                  (relates_to . "$root") (relation_type . "m.thread")
                  (content . ((body . "Older")))))
         (room (get-buffer-create "*gomuks-thread-source-test*"))
         (thread-name "*Gomuks thread: $root*"))
    (unwind-protect
        (save-window-excursion
          (puthash 1 root gomuks--events)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id "!room:test")
            (let ((inhibit-read-only t))
              (gomuks--insert-event late))
            (goto-char (point-min)))
          (switch-to-buffer room)
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (should (equal command "paginate_manual"))
                       (should (equal (gomuks--alist 'thread_root data) "$root"))
                       (funcall callback nil
                                (if (gomuks--alist 'since data)
                                    `((events . (,early ,older))
                                      (next_batch . ""))
                                  `((events . (,late ,early))
                                    (next_batch . "older")))))))
            (gomuks-open-thread)
            (with-current-buffer thread-name
              (should (equal gomuks--thread-root "$root"))
              (should (eq gomuks--parent-buffer room))
              (should (equal (mapcar (lambda (event)
                                       (gomuks--alist 'event_id event))
                                     gomuks--thread-events)
                             '("$root" "$early" "$late")))
              (should (equal gomuks--thread-next-batch "older"))
              (gomuks-open-thread late)
              (should (equal gomuks--thread-next-batch "older"))
              (gomuks-load-history)
              (should (equal (mapcar (lambda (event)
                                       (gomuks--alist 'event_id event))
                                     gomuks--thread-events)
                             '("$root" "$older" "$early" "$late")))
              (should-not gomuks--thread-next-batch))))
      (dolist (name (list thread-name
                          "*Gomuks compose: !room:test thread $root*"
                          "*Gomuks compose: !room:test*"))
        (when-let* ((buffer (get-buffer name))) (kill-buffer buffer)))
      (kill-buffer room))))

(ert-deftest gomuks-fetches-missing-room-member-name ()
  (let ((gomuks--stream 'test)
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--member-state (make-hash-table :test 'equal))
        (gomuks--requested-members (make-hash-table :test 'equal))
        (message-event '((rowid . 1) (sender . "@a:test")
                         (type . "m.room.message")
                         (content . ((body . "Hi")))))
        (sent nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_process) t))
              ((symbol-function 'gomuks--post)
               (lambda (command data callback)
                 (setq sent (cons command data))
                 (funcall callback nil
                          '(((rowid . 2) (room_id . "!room:test")
                             (type . "m.room.member")
                             (state_key . "@a:test")
                             (content . ((displayname . "Alice")))))))))
      (gomuks--request-missing-members "!room:test" (list message-event)))
    (should (equal (car sent) "get_specific_room_state"))
    (should (equal (gomuks--alist 'state_key
                                 (aref (gomuks--alist 'keys (cdr sent)) 0))
                   "@a:test"))
    (should (string-match-p "get_specific_room_state" (car sent)))
    (should (string-match-p "\\\"keys\\\":\\[" (json-serialize (cdr sent))))
    (should (equal (gomuks--sender-name "!room:test" message-event) "Alice"))))

(ert-deftest gomuks-stream-parses-split-json-lines ()
  (let ((gomuks--rooms (make-hash-table :test 'equal))
        (gomuks--events (make-hash-table :test 'equal))
        (gomuks--timelines (make-hash-table :test 'equal))
        (gomuks--timeline-ids (make-hash-table :test 'equal))
        (gomuks--pending ""))
    (gomuks--stream-filter nil
                           "{\"command\":\"sync_complete\",\"data\":{\"rooms\":{\"!a:b\":")
    (should-not (gethash "!a:b" gomuks--rooms))
    (gomuks--stream-filter nil
                           "{\"meta\":{\"name\":\"A\"},\"reset\":false}}}}\n")
    (should (equal (gomuks--room-name "!a:b") "A"))))

(ert-deftest gomuks-reaction-serializes-matrix-content ()
  (let ((sent nil))
    (cl-letf (((symbol-function 'gomuks--post)
               (lambda (_command data _callback) (setq sent data))))
      (with-temp-buffer
        (gomuks-room-mode)
        (setq gomuks--room-id "!a:b")
        (let ((inhibit-read-only t))
          (insert "message\n")
          (put-text-property (point-min) (point-max) 'gomuks-event
                             '((event_id . "$event"))))
        (goto-char (point-min))
        (gomuks-react "👍")))
    (should (string-match-p "m.relates_to" (json-serialize sent)))))

(ert-deftest gomuks-sticker-sends-native-event-and-keeps-draft ()
  (let ((file (make-temp-file "gomuks-sticker-test-" nil ".png")) sent)
    (unwind-protect
        (with-temp-buffer
          (gomuks-compose-mode)
          (setq gomuks--room-id "!sticker:test")
          (insert "unfinished draft")
          (cl-letf (((symbol-function 'gomuks--upload-file)
                     (lambda (_file _id callback)
                       (funcall callback nil
                                (json-parse-string
                                 "{\"msgtype\":\"m.image\",\"body\":\"sticker.png\",\"file\":{\"key\":{\"key_ops\":[\"encrypt\",\"decrypt\"]}}}"
                                 :object-type 'hash-table :array-type 'array))))
                    ((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (should (string-match-p "encrypt"
                                               (json-serialize data)))
                       (setq sent (cons command data))
                       (funcall callback nil nil))))
            (gomuks-send-sticker file))
          (should (equal (car sent) "send_message"))
          (should (equal (gethash "msgtype"
                                  (gomuks--alist 'base_content (cdr sent)))
                         "m.sticker"))
          (should (equal (gomuks--alist 'text (cdr sent)) ""))
          (should (equal (buffer-string) "unfinished draft")))
      (delete-file file))))

(ert-deftest gomuks-emoji-picker-inserts-into-draft ()
  (with-temp-buffer
    (gomuks-compose-mode)
    (cl-letf (((symbol-function 'emoji-search)
               (lambda () (interactive) (insert "😄"))))
      (gomuks-insert-emoji))
    (should (equal (buffer-string) "😄"))
    (should (eq (lookup-key gomuks-compose-mode-map (kbd "C-c C-e"))
                #'gomuks-insert-emoji))))

(ert-deftest gomuks-gif-url-downloads-image-before-sending ()
  (let (sent-bytes response-buffer)
    (with-temp-buffer
      (setq gomuks--room-id "!gif:test")
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (_url callback &rest _)
                   (setq response-buffer (generate-new-buffer " *gomuks-gif-response*"))
                   (with-current-buffer response-buffer
                     (insert "HTTP/1.1 200 OK\r\n\r\nGIF89a" (unibyte-string 0 255))
                     (setq-local url-http-response-status 200)
                     (funcall callback nil))))
                ((symbol-function 'gomuks-send-file)
                 (lambda (file &optional sticker cleanup)
                   (should-not sticker)
                   (should cleanup)
                   (setq sent-bytes
                         (with-temp-buffer
                           (insert-file-contents-literally file)
                           (buffer-string)))
                   (delete-file file))))
        (gomuks-send-gif "https://example.test/animation.gif"))
      (should (equal (encode-coding-string sent-bytes 'binary)
                     (concat "GIF89a" (unibyte-string 0 255))))
      (should-not (buffer-live-p response-buffer)))))

(ert-deftest gomuks-reaction-button-shows-senders ()
  (let* ((gomuks--rooms (make-hash-table :test 'equal))
         (gomuks--events (make-hash-table :test 'equal))
         (gomuks--member-state (make-hash-table :test 'equal))
         (gomuks--stream nil)
         (id "!reactions:test")
         (event '((event_id . "$message") (sender . "@author:test")
                  (type . "m.room.message") (content . ((body . "Hello")))
                  (reactions . (("👍" . 3) ("❤️" . 0)))))
         (reaction '((event_id . "$reaction") (sender . "@alice:test")
                     (type . "m.reaction")
                     (content . ((m.relates_to . ((key . "👍")))))))
         (room (generate-new-buffer "*gomuks-reaction-test*"))
         (list-name "*Gomuks reactions: $message 👍*")
         (sent nil))
    (unwind-protect
        (save-window-excursion
          (puthash id '((name . "Reaction room")) gomuks--rooms)
          (puthash id (let ((state (make-hash-table :test 'equal)))
                        (puthash "@alice:test" 7 state) state)
                   gomuks--member-state)
          (puthash 7 '((content . ((displayname . "Alice")))) gomuks--events)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id id)
            (let ((inhibit-read-only t)) (gomuks--insert-event event))
            (should-not (string-match-p "❤️ 0" (buffer-string))))
          (switch-to-buffer room)
          (goto-char (point-min))
          (search-forward "👍 3")
          (backward-char)
          (should (button-at (point)))
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (setq sent (cons command data))
                       (funcall callback nil
                                (list reaction reaction
                                      '((sender . "@bob:test")
                                        (redacted_by . "$redaction")
                                        (content . ((m.relates_to . ((key . "👍"))))))
                                      '((sender . "@carol:test")
                                        (content . ((m.relates_to . ((key . "👎")))))))))))
            (gomuks-activate-at-point))
          (should (equal (car sent) "get_related_events"))
          (should (equal (gomuks--alist 'relation_type (cdr sent))
                         "m.annotation"))
          (with-current-buffer list-name
            (should (string-match-p "Alice  @alice:test" (buffer-string)))
            (should-not (string-match-p "bob\\|carol" (buffer-string)))
            (should (= (how-many "@alice:test" (point-min) (point-max)) 1))))
      (when-let* ((buffer (get-buffer list-name))) (kill-buffer buffer))
      (kill-buffer room))))

(ert-deftest gomuks-removes-only-own-reaction ()
  (let* ((gomuks--user-id "@me:test")
         (gomuks--rooms (make-hash-table :test 'equal))
         (event '((event_id . "$message")))
         (own '((event_id . "$mine") (sender . "@me:test")
                (content . ((m.relates_to . ((key . "👍")))))))
         (other '((event_id . "$other") (sender . "@other:test")
                  (content . ((m.relates_to . ((key . "👍")))))))
         (buffer-name "*Gomuks reactions: $message 👍*")
         (reactions (list own other))
         redacted)
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (command data callback)
                       (pcase command
                         ("get_related_events" (funcall callback nil reactions))
                         ("redact_event"
                          (setq redacted (gomuks--alist 'event_id data)
                                reactions (list other))
                          (with-temp-buffer (funcall callback nil nil)))))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (with-temp-buffer
              (gomuks-room-mode)
              (setq gomuks--room-id "!room:test")
              (gomuks-show-reactions event "👍"))
            (with-current-buffer buffer-name
              (goto-char (point-min))
              (search-forward "other")
              (should-error (gomuks-remove-reaction) :type 'user-error)
              (goto-char (point-min))
              (should (search-forward "[d remove]" nil t))
              (gomuks-remove-reaction)
              (should (equal redacted "$mine"))
              (should-not (string-match-p "@me:test" (buffer-string))))))
      (when-let* ((buffer (get-buffer buffer-name))) (kill-buffer buffer))))))

(ert-deftest gomuks-pastes-clipboard-image-as-attachment ()
  (let ((bytes (unibyte-string 137 80 78 71 13 10 26 10 0 255))
        sent uploaded-files)
    (with-temp-buffer
      (gomuks-compose-mode)
      (setq gomuks--room-id "!room:test")
      (insert "caption")
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                ((symbol-function 'gui-get-selection)
                 (lambda (_selection type)
                   (when (eq type 'image/png) bytes)))
                ((symbol-function 'gomuks--upload-file)
                 (lambda (file _id callback)
                   (push file uploaded-files)
                   (should (equal
                            (with-temp-buffer
                              (set-buffer-multibyte nil)
                              (insert-file-contents-literally file)
                              (buffer-string)) bytes))
                   (funcall callback nil (make-hash-table :test 'equal))))
                ((symbol-function 'gomuks--post)
                 (lambda (command data callback)
                   (should (equal command "send_message"))
                   (push data sent)
                   (funcall callback nil nil))))
        (gomuks-paste-image)
        (gomuks-paste-image)
        (should-not sent)
        (should-not uploaded-files)
        (should (equal (buffer-string) "caption"))
        (should (string-match-p "2 attachments" header-line-format))
        (should (= (length gomuks--compose-attachment) 2))
        (should (cl-every #'file-exists-p
                          (mapcar #'car gomuks--compose-attachment)))
        (gomuks-compose-send))
      (setq sent (nreverse sent))
      (should (= (length sent) 2))
      (should (equal (mapcar (lambda (data) (gomuks--alist 'text data)) sent)
                     '("" "caption")))
      (should (cl-every (lambda (data) (gomuks--alist 'base_content data)) sent))
      (should (cl-every (lambda (file) (equal (file-name-extension file) "png"))
                        uploaded-files))
      (should-not (cl-some #'file-exists-p uploaded-files))
      (should-not gomuks--compose-attachment)
      (should (equal (buffer-string) "")))))

(ert-deftest gomuks-multiple-attachments-retry-only-unsent-files ()
  (let ((first (make-temp-file "gomuks-first-"))
        (second (make-temp-file "gomuks-second-"))
        (attempts nil)
        (fail-second t))
    (unwind-protect
        (with-temp-buffer
          (gomuks-compose-mode)
          (setq gomuks--room-id "!room:test")
          (insert "caption")
          (gomuks-send-file first)
          (gomuks-send-file second)
          (cl-letf (((symbol-function 'gomuks--upload-file)
                     (lambda (file _id callback)
                       (let ((content (make-hash-table :test 'equal)))
                         (puthash "body" (file-name-nondirectory file) content)
                         (funcall callback nil content))))
                    ((symbol-function 'gomuks--post)
                     (lambda (_command data callback)
                       (push (cons (gethash "body" (gomuks--alist 'base_content data))
                                   (gomuks--alist 'text data)) attempts)
                       (if (and fail-second
                                (equal (gethash "body" (gomuks--alist 'base_content data))
                                       (file-name-nondirectory second)))
                           (progn (setq fail-second nil)
                                  (funcall callback "send failed" nil))
                         (funcall callback nil nil)))))
            (gomuks-compose-send)
            (should (equal (reverse attempts)
                           (list (cons (file-name-nondirectory first) "")
                                 (cons (file-name-nondirectory second) "caption"))))
            (should (= (length gomuks--compose-attachment) 1))
            (should (equal (caar gomuks--compose-attachment) second))
            (should (equal (buffer-string) "caption"))
            (should-not gomuks--compose-sending)
            (gomuks-compose-send)
            (should (= (length attempts) 3))
            (should-not gomuks--compose-attachment)
            (should (equal (buffer-string) ""))))
      (delete-file first)
      (delete-file second))))

(ert-deftest gomuks-remove-one-of-several-staged-attachments ()
  (let ((first (make-temp-file "gomuks-first-"))
        (second (make-temp-file "gomuks-second-")))
    (with-temp-buffer
      (gomuks-compose-mode)
      (setq gomuks--room-id "!room:test")
      (gomuks--stage-attachment first t "first")
      (gomuks--stage-attachment second t "second")
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _) (car (cadr choices)))))
        (gomuks-compose-remove-attachment))
      (should (equal (mapcar #'car gomuks--compose-attachment) (list first)))
      (should (file-exists-p first))
      (should-not (file-exists-p second))
      (gomuks--cleanup-compose-attachment))
    (should-not (file-exists-p first))))

(ert-deftest gomuks-preview-removes-the-selected-image ()
  (let ((first (make-temp-file "gomuks-first-" nil ".png"))
        (second (make-temp-file "gomuks-second-" nil ".png"))
        (composer (generate-new-buffer " *gomuks-preview-compose*")))
    (unwind-protect
        (save-window-excursion
          (with-current-buffer composer
            (gomuks-compose-mode)
            (setq gomuks--room-id "!room:test")
            (gomuks--stage-attachment first t "first")
            (gomuks--stage-attachment second t "second"))
          (switch-to-buffer composer)
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt choices &rest _) (car (cadr choices))))
                    ((symbol-function 'display-images-p) (lambda (&rest _) t))
                    ((symbol-function 'image-type-from-file-name)
                     (lambda (_file) 'png))
                    ((symbol-function 'create-image)
                     (lambda (&rest _) 'test-image))
                    ((symbol-function 'insert-image)
                     (lambda (&rest _) (insert "[image]"))))
            (gomuks-compose-preview-attachment))
          (should (derived-mode-p 'gomuks-attachment-preview-mode))
          (should (string-match-p "\[image\]" (buffer-string)))
          (gomuks-attachment-preview-remove)
          (with-current-buffer composer
            (should (equal (mapcar #'car gomuks--compose-attachment)
                           (list first))))
          (let (opened)
            (switch-to-buffer composer)
            (cl-letf (((symbol-function 'display-images-p)
                       (lambda (&rest _) nil))
                      ((symbol-function 'browse-url-of-file)
                       (lambda (file &rest _) (setq opened file))))
              (gomuks-compose-preview-attachment)
              (should (string-match-p "Press RET" (buffer-string)))
              (gomuks-attachment-preview-open)
              (should (equal opened first)))))
      (when (buffer-live-p composer) (kill-buffer composer))
      (when-let* ((preview (get-buffer "*Gomuks attachment preview*")))
        (kill-buffer preview)))
    (should-not (file-exists-p first))
    (should-not (file-exists-p second))))

(ert-deftest gomuks-staged-attachment-survives-failure-and-can-be-removed ()
  (let ((file (make-temp-file "gomuks-stage-test-" nil ".png")))
    (unwind-protect
        (with-temp-buffer
          (gomuks-compose-mode)
          (setq gomuks--room-id "!room:test")
          (insert "caption")
          (cl-letf (((symbol-function 'gomuks--upload-file)
                     (lambda (_file _id callback)
                       (funcall callback "upload failed" nil))))
            (gomuks-send-file file)
            (should gomuks--compose-attachment)
            (should-not gomuks--compose-sending)
            (gomuks-compose-send))
          (should gomuks--compose-attachment)
          (should-not gomuks--compose-sending)
          (should (equal (buffer-string) "caption"))
          (gomuks-compose-remove-attachment)
          (should-not gomuks--compose-attachment)
          (should (file-exists-p file)))
      (delete-file file))))

(ert-deftest gomuks-room-header-stays-outside-timeline ()
  (let* ((gomuks--rooms (make-hash-table :test 'equal))
         (gomuks--timelines (make-hash-table :test 'equal))
         (gomuks--stream nil)
         (id "!header:test")
         (room (generate-new-buffer "*gomuks-header-test*")))
    (unwind-protect
        (save-window-excursion
          (puthash id '((name . "Header room") (topic . "Always visible"))
                   gomuks--rooms)
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id id))
          (switch-to-buffer room)
          (gomuks--render-buffer room id)
          (with-current-buffer room
            (should (string-match-p "Header room.*Always visible"
                                    (substring-no-properties header-line-format)))
            (should-not (string-match-p "Header room" (buffer-string)))))
      (kill-buffer room))))

(ert-deftest gomuks-composer-sends-multiline-and-clears-on-success ()
  (let ((sent nil)
        (room (generate-new-buffer "*gomuks-test-room*"))
        (composer nil))
    (unwind-protect
        (progn
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id "!room:test"))
          (setq composer (gomuks--composer-buffer room))
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (_command data callback)
                       (setq sent data)
                       (funcall callback nil nil))))
            (with-current-buffer composer
              (insert "First line\nsecond line")
              (gomuks-compose-send)
              (should (string-empty-p (buffer-string)))))
          (should (equal (gomuks--alist 'text sent)
                         "First line\nsecond line")))
      (when (buffer-live-p composer) (kill-buffer composer))
      (kill-buffer room))))

(ert-deftest gomuks-thread-composer-keeps-draft-on-error ()
  (let ((sent nil)
        (room (generate-new-buffer "*gomuks-test-thread*"))
        (composer nil))
    (unwind-protect
        (progn
          (with-current-buffer room
            (gomuks-room-mode)
            (setq gomuks--room-id "!room:test"
                  gomuks--thread-root "$root"))
          (setq composer (gomuks--composer-buffer room))
          (cl-letf (((symbol-function 'gomuks--post)
                     (lambda (_command data callback)
                       (setq sent data)
                       (funcall callback "HTTP 500" nil))))
            (with-current-buffer composer
              (insert "keep this draft")
              (gomuks-compose-send)
              (should (equal (buffer-string) "keep this draft"))
              (should-not gomuks--compose-sending)))
          (should (equal (gomuks--alist 'rel_type
                                       (gomuks--alist 'relates_to sent))
                         "m.thread")))
      (when (buffer-live-p composer) (kill-buffer composer))
      (kill-buffer room))))

(ert-deftest gomuks-attachment-renders-open-and-save-actions ()
  (let ((gomuks-inline-images nil))
    (with-temp-buffer
      (gomuks-room-mode)
      (setq gomuks--room-id "!room:test")
      (let ((inhibit-read-only t))
        (gomuks--insert-event
         '((rowid . 1) (sender . "@a:test") (type . "m.room.message")
           (content . ((msgtype . "m.image") (body . "photo.png")
                       (url . "mxc://server/id")
                       (info . ((size . 1234) (mimetype . "image/png"))))))))
      (should (string-match-p "photo.png" (buffer-string)))
      (should (eq (lookup-key gomuks-room-mode-map (kbd "o"))
                  #'gomuks-open-attachment))
      (should (eq (lookup-key gomuks-room-mode-map (kbd "D"))
                  #'gomuks-save-attachment))
      (should (eq (lookup-key gomuks-room-mode-map (kbd "d d"))
                  #'gomuks-redact))
      (should (eq (lookup-key gomuks-room-mode-map (kbd "C-c C-o"))
                  #'gomuks-open-attachment))
      (should (eq (lookup-key gomuks-room-mode-map (kbd "C-c C-w"))
                  #'gomuks-save-attachment))
      (goto-char (point-min))
      (search-forward "photo.png")
      (should (= 1 (gomuks--alist 'rowid (gomuks--event-at-point))))
      (goto-char (point-min))
      (should (search-forward "Open" nil t))
      (should (= 1 (gomuks--alist 'rowid (gomuks--event-at-point))))
      (should (button-at (1- (point)))))))

(ert-deftest gomuks-ogg-attachment-plays-through-empv ()
  (let (played)
    (cl-letf (((symbol-function 'gomuks--fetch-media)
               (lambda (_attachment callback) (funcall callback "/tmp/voice.ogg")))
              ((symbol-function 'require)
               (lambda (feature &rest _) (eq feature 'empv)))
              ((symbol-function 'empv-play)
               (lambda (path) (setq played path))))
      (gomuks-open-attachment
       '((content . ((msgtype . "m.file") (body . "voice.ogg")
                     (url . "mxc://server/voice"))))))
    (should (equal played "/tmp/voice.ogg"))))

(ert-deftest gomuks-dd-redacts-whole-message-after-confirmation ()
  (let (sent)
    (with-temp-buffer
      (gomuks-room-mode)
      (setq gomuks--room-id "!room:test")
      (let ((inhibit-read-only t))
        (insert "first line\nsecond line\n")
        (put-text-property (point-min) (point-max) 'gomuks-event
                           '((event_id . "$message"))))
      (goto-char (point-min))
      (forward-line 1)
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
                ((symbol-function 'gomuks--post)
                 (lambda (command data _callback)
                   (setq sent (cons command data)))))
        (call-interactively (lookup-key gomuks-room-mode-map (kbd "d d")))))
    (should (equal (car sent) "redact_event"))
    (should (equal (gomuks--alist 'event_id (cdr sent)) "$message"))))

(ert-deftest gomuks-message-links-are-clickable ()
  (let ((opened nil))
    (with-temp-buffer
      (gomuks-room-mode)
      (setq gomuks--room-id "!room:test")
      (let ((inhibit-read-only t))
        (gomuks--insert-event
         '((rowid . 1) (event_id . "$link") (sender . "@a:test")
           (type . "m.room.message")
           (content . ((body . "Read https://example.org/docs?x=1."))))))
      (goto-char (point-min))
      (search-forward "https://example.org/docs?x=1")
      (backward-char)
      (let ((button (button-at (point))))
        (should button)
        (should (equal (button-get button 'url)
                       "https://example.org/docs?x=1"))
        (should (equal "$link"
                       (gomuks--alist 'event_id (gomuks--event-at-point))))
        (cl-letf (((symbol-function 'browse-url)
                   (lambda (url &rest _) (setq opened url))))
          (gomuks-activate-at-point))
        (should (equal opened "https://example.org/docs?x=1"))))))

(ert-deftest gomuks-home-restores-window-layout ()
  (let ((gomuks--previous-window-config nil)
        (original-buffer (window-buffer (selected-window))))
    (unwind-protect
        (save-window-excursion
          (gomuks-home)
          (should (eq (current-buffer) (get-buffer "*Gomuks*")))
          (should (= (length (window-list)) 1))
          (gomuks-quit)
          (should (eq (window-buffer (selected-window)) original-buffer)))
      (when-let* ((buffer (get-buffer "*Gomuks*"))) (kill-buffer buffer)))))

(provide 'gomuks-tests)
;;; gomuks-tests.el ends here
